version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: notesas-be:latest
    container_name: notesas_app
    ports:
      - "8080:8080"
    env_file:
      - ../.env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fhamb_net

networks:
  backend_network:
    driver: bridge
